version: 1
formatters:
  printer1:
    format: '%(asctime)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  precise:
    format: '%(asctime)s - %(funcName)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class : logging.StreamHandler
    formatter: printer1
    level   : INFO
    stream  : ext://sys.stdout
  file_NOWA:
    class : logging.FileHandler
    formatter: precise
    filename: logs/file_NOWA.log
    mode: a
    level: DEBUG
loggers:
  printer:
    handlers: [console, file_NOWA]
    level: DEBUG
  printer_NOWA:
    handlers: [console, file_NOWA]
    level: DEBUG
  